/**
 * Base docker-compose template: OpenClaw only (builtin processor).
 * Security: read-only rootfs, resource limits, tmpfs for writable dirs.
 */
export function baseComposeTemplate(name: string, port: number): string {
  return `# Generated by claw-farm — ${name}
services:
  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "127.0.0.1:${port}:18789"
    volumes:
      - ./openclaw/config:/home/node/.openclaw:ro
      - ./openclaw/workspace:/home/node/.openclaw/workspace
      - ./openclaw/raw/sessions:/home/node/.openclaw/sessions
      - ./openclaw/config/policy.yaml:/home/node/.openclaw/policy.yaml:ro
      - ./logs:/home/node/.openclaw/logs
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      OPENCLAW_SANDBOX: 1
      OPENCLAW_AUDIT_LOG: /home/node/.openclaw/logs/audit.jsonl
    read_only: true
    tmpfs:
      - /tmp:size=100M
      - /home/node/.cache:size=200M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 128M
    restart: unless-stopped
`;
}
