import { portRange } from "../lib/ports.ts";

/**
 * Mem0+Qdrant docker-compose template: 3-tier stack.
 * Security: network isolation, read-only rootfs, resource limits, no raw env secrets in agent.
 */
export function mem0ComposeTemplate(name: string, port: number): string {
  const ports = portRange(port);
  return `# Generated by claw-farm — ${name} (mem0 processor)
services:
  qdrant:
    image: qdrant/qdrant:v1.13.0
    expose:
      - "6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  mem0-api:
    build: ./mem0
    ports:
      - "127.0.0.1:${ports.mem0}:8050"
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      MEM0_API_KEY: \${MEM0_API_KEY}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    networks:
      - frontend
      - backend
    read_only: true
    tmpfs:
      - /tmp:size=100M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8050/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "127.0.0.1:${ports.openclaw}:18789"
    volumes:
      - ./openclaw/config:/home/node/.openclaw:ro
      - ./openclaw/workspace:/home/node/.openclaw/workspace
      - ./openclaw/raw/sessions:/home/node/.openclaw/sessions
      - ./openclaw/config/policy.yaml:/home/node/.openclaw/policy.yaml:ro
      - ./logs:/home/node/.openclaw/logs
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      OPENCLAW_SANDBOX: 1
      OPENCLAW_AUDIT_LOG: /home/node/.openclaw/logs/audit.jsonl
    networks:
      - frontend
    read_only: true
    tmpfs:
      - /tmp:size=100M
      - /home/node/.cache:size=200M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 128M
    depends_on:
      mem0-api:
        condition: service_healthy
    restart: unless-stopped

networks:
  frontend:
    internal: false
  backend:
    internal: true
`;
}
