/**
 * Base docker-compose template: OpenClaw only (builtin processor).
 */
export function baseComposeTemplate(name: string, port: number): string {
  return `# Generated by claw-farm — ${name}
services:
  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "127.0.0.1:${port}:18789"
    volumes:
      - ./openclaw/config:/home/node/.openclaw:ro
      - ./openclaw/workspace:/home/node/.openclaw/workspace
      - ./openclaw/raw/sessions:/home/node/.openclaw/sessions
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      OPENCLAW_SANDBOX: 1
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped
`;
}
