import { portRange } from "../lib/ports.ts";

/**
 * Mem0+Qdrant docker-compose template: 3-tier stack.
 */
export function mem0ComposeTemplate(name: string, port: number): string {
  const ports = portRange(port);
  return `# Generated by claw-farm — ${name} (mem0 processor)
services:
  qdrant:
    image: qdrant/qdrant:v1.13.0
    expose:
      - "6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  mem0-api:
    build: ./mem0
    ports:
      - "127.0.0.1:${ports.mem0}:8050"
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      MEM0_API_KEY: \${MEM0_API_KEY}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    networks:
      - frontend
      - backend
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8050/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "127.0.0.1:${ports.openclaw}:18789"
    volumes:
      - ./openclaw/config:/home/node/.openclaw:ro
      - ./openclaw/workspace:/home/node/.openclaw/workspace
      - ./openclaw/raw/sessions:/home/node/.openclaw/sessions
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      OPENCLAW_SANDBOX: 1
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      mem0-api:
        condition: service_healthy
    restart: unless-stopped

networks:
  frontend:
  backend:
`;
}
