/**
 * Nginx reverse proxy config for cloud deployment.
 * Adds auth, rate limiting, and TLS termination in front of OpenClaw.
 */
export function nginxProxyTemplate(name: string, port: number): string {
  return `# Nginx reverse proxy for ${name} — generated by claw-farm
# Place behind Coolify's built-in SSL or use certbot for standalone

upstream openclaw_${name.replace(/-/g, "_")} {
    server 127.0.0.1:${port};
}

# Rate limiting zone
limit_req_zone $binary_remote_addr zone=${name}:10m rate=10r/s;

server {
    listen 443 ssl http2;
    server_name ${name}.example.com;  # Change to your domain

    # TLS — managed by Coolify or certbot
    # ssl_certificate /etc/letsencrypt/live/${name}.example.com/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/${name}.example.com/privkey.pem;

    # Security headers
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # Rate limiting
    limit_req zone=${name} burst=20 nodelay;
    limit_req_status 429;

    # Basic auth (generate with: htpasswd -c /etc/nginx/.htpasswd admin)
    auth_basic "OpenClaw — ${name}";
    auth_basic_user_file /etc/nginx/.htpasswd;

    # IP allowlist (uncomment and edit for extra security)
    # allow 1.2.3.4;    # your IP
    # allow 10.0.0.0/8; # Tailscale
    # deny all;

    # Request size limit
    client_max_body_size 10M;

    location / {
        proxy_pass http://openclaw_${name.replace(/-/g, "_")};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeouts for long-running LLM requests
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    # Block direct access to internal APIs
    location /internal/ {
        deny all;
        return 404;
    }
}
`;
}
