import { loadRegistry } from "../lib/registry.ts";
import { readProjectConfig } from "../lib/config.ts";
import { portRange } from "../lib/ports.ts";

export async function cloudComposeCommand(args: string[]): Promise<void> {
  const reg = await loadRegistry();
  const names = Object.keys(reg.projects);

  if (names.length === 0) {
    console.log("No projects registered. Run: claw-farm init <name>");
    return;
  }

  const outFile = args.find((a) => !a.startsWith("-")) ?? "docker-compose.cloud.yml";

  let services = "";
  let networks = "networks:\n";
  const usedNetworks = new Set<string>();

  for (const name of names) {
    const entry = reg.projects[name];
    const config = await readProjectConfig(entry.path);
    const processor = config?.processor ?? entry.processor;
    const ports = portRange(entry.port);

    // OpenClaw service (always present)
    services += `  ${name}-openclaw:
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "${ports.openclaw}:18789"
    volumes:
      - ./${name}/openclaw/config:/home/node/.openclaw:ro
      - ./${name}/openclaw/workspace:/home/node/.openclaw/workspace
      - ./${name}/openclaw/raw/sessions:/home/node/.openclaw/sessions
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      OPENCLAW_SANDBOX: 1
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped
`;

    if (processor === "mem0") {
      const netName = `${name}-net`;
      usedNetworks.add(netName);

      services += `    networks:
      - ${netName}
    depends_on:
      ${name}-mem0:
        condition: service_healthy

  ${name}-qdrant:
    image: qdrant/qdrant:v1.13.0
    expose:
      - "6333"
    volumes:
      - ./${name}/data/qdrant:/qdrant/storage
    networks:
      - ${netName}
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  ${name}-mem0:
    build: ./${name}/mem0
    ports:
      - "${ports.mem0}:8050"
    environment:
      GEMINI_API_KEY: \${GEMINI_API_KEY}
      MEM0_API_KEY: \${MEM0_API_KEY}
      QDRANT_HOST: ${name}-qdrant
      QDRANT_PORT: 6333
    networks:
      - ${netName}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      ${name}-qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8050/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

`;
    } else {
      services += "\n";
    }
  }

  for (const net of usedNetworks) {
    networks += `  ${net}:\n`;
  }

  const compose = `# Generated by claw-farm cloud:compose
# Deploy this with Coolify or any Docker Compose host
services:
${services}${usedNetworks.size > 0 ? networks : ""}`;

  await Bun.write(outFile, compose);
  console.log(`\n✅ Cloud compose written to: ${outFile}`);
  console.log(`   Includes ${names.length} project(s): ${names.join(", ")}\n`);
}
